name: Deploy via ftp
on: push
permissions:
  contents: read
  
jobs:
  deploy:
    name: Checkout and Upload
    runs-on: ubuntu-latest
    steps:
    - uses: joutvhu/ftp-transfer@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        commands: |
          put ./ ./
